config/routes.rb
Rails.application.routes.draw do
  resources :howtoplaygames
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

	has_one :howtoplaygame
	has_attached_file :avatar, styles: {medium: "850x350#"}, default_url: "http://placehold.it/850x350"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/howtoplaygame.rb
class Howtoplaygame < ApplicationRecord

belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :genre, :rating, :avatar)
    end
end

app/controllers/howtoplaygames_controller.rb
class HowtoplaygamesController < ApplicationController
  before_action :set_howtoplaygame, only: [:show, :edit, :update, :destroy]

  # GET /howtoplaygames
  # GET /howtoplaygames.json
  def index
    @howtoplaygames = Howtoplaygame.all
  end

  # GET /howtoplaygames/1
  # GET /howtoplaygames/1.json
  def show
    @howtoplaygame = Howtoplaygame.find_by_game_id(params[:id])
  end

  # GET /howtoplaygames/new
  def new
    @howtoplaygame = Howtoplaygame.new
  end

  # GET /howtoplaygames/1/edit
  def edit
  end

  # POST /howtoplaygames
  # POST /howtoplaygames.json
  def create
    @howtoplaygame = Howtoplaygame.new(howtoplaygame_params)

    respond_to do |format|
      if @howtoplaygame.save
        format.html { redirect_to @howtoplaygame, notice: 'Howtoplaygame was successfully created.' }
        format.json { render :show, status: :created, location: @howtoplaygame }
      else
        format.html { render :new }
        format.json { render json: @howtoplaygame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /howtoplaygames/1
  # PATCH/PUT /howtoplaygames/1.json
  def update
    respond_to do |format|
      if @howtoplaygame.update(howtoplaygame_params)
        format.html { redirect_to @howtoplaygame, notice: 'Howtoplaygame was successfully updated.' }
        format.json { render :show, status: :ok, location: @howtoplaygame }
      else
        format.html { render :edit }
        format.json { render json: @howtoplaygame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /howtoplaygames/1
  # DELETE /howtoplaygames/1.json
  def destroy
    @howtoplaygame.destroy
    respond_to do |format|
      format.html { redirect_to howtoplaygames_url, notice: 'Howtoplaygame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_howtoplaygame
      @howtoplaygame = Howtoplaygame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def howtoplaygame_params
      params.require(:howtoplaygame).permit(:instructions, :game_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/howtoplaygames_helper.rb
module HowtoplaygamesHelper
end

app/views/games/_form.html.haml
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :genre
    = f.text_field :genre
  .field
    = f.label :rating
    = f.number_field :rating
  .field
    = f.label :avatar
    = f.file_field :avatar

  .actions
    = f.submit 'Save'

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
!!!
%html.no-js{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Foundation | Welcome
    %link{:href => "http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css", :rel => "stylesheet"}/
    %link{:href => "http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css", :rel => "stylesheet", :type => "text/css"}/
  %body
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-2195009-2', 'auto');
      ga('send', 'pageview');

      ga('create', 'UA-2195009-27', 'auto', {name: "foundation"});
      ga('foundation.send', 'pageview');
    .top-bar
      .top-bar-left
        %ul.menu
          %li.menu-text Blog
          %li
            %a{:href => "#"} One
          %li
            %a{:href => "#"} Two
          %li
            %a{:href => "#"} Three
    .callout.large.primary
      .row.column.text-center
        %h1 the girl gamer
        %h2.subheader Games I Love :)
    - @games.order(:created_at).each do |game|
      .row.medium-8.large-7.columns
        .blog-post
          %h3
            = game.name
            %small= "#{game.created_at.strftime("%m/%d/%y")}"
            .button-group.round
              %a.button.mr-poopy-pants{:href => edit_game_path(game.id)} Edit
              %a.button.grape{:href => howtoplaygame_path(game.id)} Instructions
              = link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert radius'
          = image_tag game.avatar.url(:medium)
          %p= game.description
          .callout
          %ul.menu.simple
            %li
              %a{:href => "#"} Author: Celia
            %li
              %a{:href => "#"} Comments: 3
      
    %script{:src => "https://code.jquery.com/jquery-2.1.4.min.js"}
    %script{:src => "http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"}
    :javascript
      $(document).foundation();
    %script{:src => "https://intercom.zurb.com/scripts/zcom.js", :type => "text/javascript"}

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @game.name
%p
  %b Description:
  = @game.description
%p
  %b Genre:
  = @game.genre
%p
  %b Rating:
  = @game.rating

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path

app/views/games/test.html.haml
test.html.haml

app/views/howtoplaygames/_form.html.haml
= form_for @howtoplaygame do |f|
  - if @howtoplaygame.errors.any?
    #error_explanation
      %h2= "#{pluralize(@howtoplaygame.errors.count, "error")} prohibited this howtoplaygame from being saved:"
      %ul
        - @howtoplaygame.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :instructions
    = f.text_area :instructions
  .field
    = f.label :game_id
    = f.select :game_id, Game.all.collect { |g| [g.name, g.id]}
  .actions
    = f.submit 'Save'

app/views/howtoplaygames/edit.html.haml
%h1 Editing howtoplaygame

= render 'form'

= link_to 'Show', @howtoplaygame
\|
= link_to 'Back', howtoplaygames_path

app/views/howtoplaygames/index.html.haml
%h1 Listing howtoplaygames

%table
  %thead
    %tr
      %th Instructions
      %th Game
      %th
      %th
      %th

  %tbody
    - @howtoplaygames.each do |howtoplaygame|
      %tr
        %td= howtoplaygame.instructions
        %td= howtoplaygame.game_id
        %td= link_to 'Show', howtoplaygame
        %td= link_to 'Edit', edit_howtoplaygame_path(howtoplaygame)
        %td= link_to 'Destroy', howtoplaygame, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Howtoplaygame', new_howtoplaygame_path

app/views/howtoplaygames/new.html.haml
%h1 New howtoplaygame

= render 'form'

= link_to 'Back', howtoplaygames_path

app/views/howtoplaygames/show.html.haml
%p#notice= notice

%p
  %b Instructions:
  = @howtoplaygame.instructions
%p
  %b Game:
  = @howtoplaygame.game_id

= link_to 'Edit', edit_howtoplaygame_path(@howtoplaygame)
\|
= link_to 'Back', howtoplaygames_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Thegirlgamer
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield